Repository kubermatic/terraform-provider-kubermatic, pull requests merged in 2020-05, with the labels that each got.

#3 Update README
  CONTRIBUTING.md
  LICENSE
  NOTICE
  README.md
Labels: approved, lgtm

#5 Add ps team
  OWNERS.txt
  OWNERS_ALIASES.txt
Labels: approved, dco-signoff: yes, lgtm, size/XS

#6 fix OWNERS and OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, lgtm, size/XS

#8 project resource related changes and acceptance tests
  Makefile
  go.mod
  kubermatic/provider.go
  kubermatic/provider_test.go
  kubermatic/resource_cluster.go
  kubermatic/resource_node_deployment.go
  kubermatic/resource_project.go
  kubermatic/resource_project_test.go
  kubermatic/sweeper_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#9 Add `kubermatic_sshkey` resource
  .gitignore
  Makefile
  go.mod
  go.sum
  kubermatic/provider.go
  kubermatic/resource_cluster.go
  kubermatic/resource_node_deployment.go
  kubermatic/resource_project_test.go
  kubermatic/resource_sshkey.go
  kubermatic/resource_sshkey_test.go
  kubermatic/sweeper_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#13 OpenStack cluster
  Makefile
  go.mod
  kubermatic/provider_test.go
  kubermatic/resource_cluster.go
  kubermatic/resource_cluster_test.go
  kubermatic/resource_project.go
  kubermatic/resource_project_test.go
  kubermatic/resource_sshkey_test.go
  kubermatic/schema_cluster.go
  kubermatic/schema_node_deployment.go
  kubermatic/structure_cluster.go
  kubermatic/structure_cluster_test.go
Labels: approved, dco-signoff: yes, lgtm, size/XXL
