Repository kubermatic/terraform-provider-kubermatic, pull requests merged in 2020-06, with the labels that each got.

#16 improve error handling from client, fix cluster deletion
  kubermatic/provider.go
  kubermatic/resource_cluster.go
  kubermatic/resource_node_deployment.go
  kubermatic/resource_project.go
  kubermatic/resource_sshkey.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#10 add furkhat as a maintainer
  OWNERS
  OWNERS_ALIASES
Labels: approved, dco-signoff: yes, do-not-merge/invalid-owners-file, lgtm, size/XS

#15 Azure cloud provider + Openstack NodeDeployments + Project users
  go.mod
  go.sum
  kubermatic/misc.go
  kubermatic/provider.go
  kubermatic/provider_test.go
  kubermatic/resource_cluster.go
  kubermatic/resource_cluster_test.go
  kubermatic/resource_node_deployment.go
  kubermatic/resource_node_deployment_test.go
  kubermatic/resource_project.go
  kubermatic/resource_project_test.go
  kubermatic/resource_service_account.go
  kubermatic/resource_service_account_test.go
  kubermatic/resource_service_account_token.go
  kubermatic/resource_service_account_token_test.go
  kubermatic/resource_sshkey.go
  kubermatic/resource_sshkey_test.go
  kubermatic/schema_cluster.go
  kubermatic/schema_node_deployment.go
  kubermatic/structure_cluster.go
  kubermatic/structure_cluster_test.go
  kubermatic/structure_node_deployment.go
  kubermatic/structure_node_deployment_test.go
  kubermatic/sweeper_test.go
Labels: approved, dco-signoff: no, lgtm, size/XXL
