Repository kubermatic/terraform-provider-kubermatic, pull requests merged in 2020-09, with the labels that each got.

#12 Add basic documentation with AWS examples
  kubermatic/provider.go
  kubermatic/resource_cluster.go
  kubermatic/schema_cluster.go
  kubermatic/schema_node_deployment.go
  website/docs/index.html.markdown
  website/docs/r/cluster.index.markdown
  website/docs/r/node_deployment.index.markdown
  website/docs/r/project.index.markdown
  website/kubermatic.erb
Labels: approved, dco-signoff: yes, lgtm, size/L

#26 add AWS example
  examples/README.md
  examples/aws/README.md
  examples/aws/main.tf
  examples/aws/variables.tf
  kubermatic/resource_cluster.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#28 simplify validateOnlyOneCloudProviderSpecified method
  kubermatic/resource_cluster.go
  kubermatic/schema_cluster.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#30 allow update action when cluster version was changed
  kubermatic/provider.go
  kubermatic/schema_cluster.go
Labels: approved, dco-signoff: yes, lgtm, size/XS
